### ISSUE TITLE
[trigger-github-issues-from-crashlytics] `POSTINSTALL` params don't match ones in `extension.yaml`

### ISSUE THREAD

**Issue by pr-Mais** [htsuruo/firebase-extensions#1]
Hello!

Noticed that the params in `POSTINSTALL` don't match the ones in `extension.yaml` which would look like this in the console:
![Screenshot 2023-05-30 at 12 06 15 PM](https://github.com/HTsuruo/firebase-extensions/assets/41123719/694dca6d-b173-409f-af4f-97b776f7b22c)

**Comment by HTsuruo** [comment]
It is my mistake, thank you for creating issue and PR (#2)

**Comment by htsuruo** [comment]
@pr-Mais 

It is my mistake, thank you for creating issue and PR (#2)
