### ISSUE TITLE
[back-up-firestore-to-storage] Schedule or time zone is invalid.

### ISSUE THREAD

**Issue by joaohenriquesfr** [htsuruo/firebase-extensions#16]
Hello, I'm getting this error even tho I've set "every 24 hours". Here is a screenshot just incase: http://prntscr.com/SYpJ0bo2A0D9

{"code":400,"message":"Schedule or time zone is invalid.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request"

**Comment by htsuruo** [comment]
@RedFr4me 

Thanks for your report.
I’ll check it later.

**Comment by htsuruo** [comment]
@RedFr4me 

I confirmed to reproduce the same behavior to your reporting.
I'll fix it.

> ; RESOURCE_ERROR at /deployments/firebase-ext-back-up-firestore-to-storage/resources/firebase-ext-back-up-firestore-to-storage-backupTransaction: {"ResourceType":"gcp-types/cloudscheduler-v1:projects.locations.jobs","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Schedule or time zone is invalid.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://cloudscheduler.googleapis.com/v1/projects/[project-id]/locations/us-central1/jobs","httpMethod":"POST"}}

**Comment by htsuruo** [comment]
> Cron jobs are scheduled at recurring intervals, specified using a format based on [unix-cron](https://man7.org/linux/man-pages/man5/crontab.5.html). You can define a schedule so that your job runs multiple times a day, or runs on specific days and months. (**Although we no longer recommend its use**, the legacy [App Engine cron syntax](https://cloud.google.com/appengine/docs/standard/python/config/cronref) is still supported for existing jobs.)

ref. https://cloud.google.com/scheduler/docs/configuring/cron-job-schedules

**Comment by htsuruo** [comment]
| Parameter | Result |
|--------|--------|
| every day 0:00 | ◯ |
| every 5 minutes | ◯ |
| every 24 hours | ✗ |

**Comment by htsuruo** [comment]
@RedFr4me 

I Investigated this issue, and then recognized that `Location` parameter is invalid.
This extension provides `Iowa (us-central1)`, but the location disappears. Please visit following reference.
https://cloud.google.com/compute/docs/regions-zones?hl=en#available

I'll update the selection list of `Location` parameter, so please wait for few days.

**Comment by htsuruo** [comment]
@RedFr4me 

I found that the setting default to UTC if `Location` is empty does not work. It's a bug of this extension.
I'll fix it. 

A workaround is here.
- Set `UTC`  in the `Location` parameter manually.

<img width="460" alt="image" src="https://github.com/htsuruo/firebase-extensions/assets/12729025/c44b44d4-ce77-43f8-85c1-45adfead9526">

**Comment by htsuruo** [comment]
Fixed with `v0.0.6` and released in Extensions Hub.
