### ISSUE TITLE
[back-up-firestore-to-storage] How load the backup?

### ISSUE THREAD

**Issue by salime45** [htsuruo/firebase-extensions#19]
Hi, 

I dont see any option for recover the data. How is this ?

Thnaks

**Comment by htsuruo** [comment]
@salime45 

Hi, you can import the backup data with Google Cloud console or `gcloud` command.
For more details, visit [Import all documents from an export](https://firebase.google.com/docs/firestore/manage-data/export-import#import_all_documents_from_an_export).
And also, I published a blog for this operation. Please check it out.
https://medium.com/@htsuruo/introducing-the-extension-for-firestore-scheduled-backups-faa902917a30#9105

Here is an example. 
If it is completed successfully, you can see following output in your console.

```bash
❯ gcloud firestore import gs://htsuruo-firestore-backup/2023-06-11T14:30:00_549
Waiting for [projects/[PROJECT_ID]/databases/(default)/operations/AiAyMDQwNTU4NTUJGnRsdWFmZWQHEjF0c2FlaHRyb24tYWlzYS1zYm9qLW5
pbWRhGgoyEg] to finish...done.
metadata:
  '@type': type.googleapis.com/google.firestore.admin.v1.ImportDocumentsMetadata
  inputUriPrefix: gs://htsuruo-firestore-backup/2023-06-11T14:30:00_549
  operationState: PROCESSING
  startTime: '2023-06-11T05:42:46.574762Z'
name: projects/[PROJECT_ID]/databases/(default)/operations/AiAyMDQwNTU4NTUJGnRsdWFmZWQHEjF0c2FlaHRyb24tYWlzYS1zYm9qLW5pbWRhGgoyEg
```

**Comment by htsuruo** [comment]
@salime45 

How about after that?

**Comment by salime45** [comment]
Perfect, thanks
