### ISSUE TITLE
[back-up-firestore-to-storage] FR: Parameter for custom folder name format

### ISSUE THREAD

**Issue by danbaechtold** [htsuruo/firebase-extensions#7]
It would be great to be able to choose a different outputUriPrefix, as not all OS support folder names with colons, for example.

A parameter to choose the timestamp format, passed to the formatTimestamp function would help.

**Comment by htsuruo** [comment]
@danbaechtold 

Thanks for your request again. 

> A parameter to choose the timestamp format, passed to the formatTimestamp function would help.

Sounds good 👍

**Comment by htsuruo** [comment]
@danbaechtold 

I have completed the resolution for this issue and released version [v0.0.4](https://github.com/HTsuruo/firebase-extensions/releases/tag/back-up-firestore-to-storage%2Fv0.0.4).
If you update the extension, you can use the `TIMESTAMP_FORMAT` parameter.

Thanks.

**Comment by danbaechtold** [comment]
Awesome, thanks! Tested it and it works great.

Just a small detail, the default text in the TIMESTAMP_FORMAT parameter seems to be wrong (month and minutes are the same because of same case, and it is not the same as in your code):
![2023-06-16 09_44_44-New Hope - Install extension - Firebase console](https://github.com/HTsuruo/firebase-extensions/assets/4057377/6ce42e0e-9655-471c-965b-8c517457d30e)

**Comment by htsuruo** [comment]
@danbaechtold 

Thanks for your report!

Hmm, It was a mistake in verification. The `example` setting should be correct, but it seems that when displayed in the GUI console, it is forcibly converted to lowercase.
https://github.com/HTsuruo/firebase-extensions/blob/a96ec5bd827dc25b60312e1628175edf97dbef35/back-up-firestore-to-storage/extension.yaml#LL86C37-L86C37

I will fix this.

**Comment by htsuruo** [comment]
> I will fix this.

Fixed and released with [v0.0.5](https://github.com/HTsuruo/firebase-extensions/releases/tag/back-up-firestore-to-storage%2Fv0.0.5)
